export  interface FilesNameType {
    documentoTipo: string;
    extension: string;
    docBase64: string;
    filename: string;
    display: string;
    accept: string;
    required: boolean;
    tab: number;
  }

export const FilesName: FilesNameType[] = [
    {
      display: "Acta Constitutiva y sus modificaciones",
      docBase64: "",
      documentoTipo: "acta",
      extension: "",
      accept: "image/*, .pdf",
      filename: "",
      required: false,
      tab: 0,
    },
    {
      display: "Registro Público del Acta Constitutiva y sus modificaciones",
      docBase64: "",
      documentoTipo: "registroPublico",
      extension: "",
      accept: "image/*, .pdf",
      filename: "",
      required: false,
      tab: 0,
    },
    {
      display: "Cédula de identificación Fiscal",
      docBase64: "",
      documentoTipo: "rfc",
      extension: "",
      accept: "image/*, .pdf",
      filename: "",
      required: false,
      tab: 0,
    },
    {
      display: "Identificación oficial",
      docBase64: "",
      documentoTipo: "ine",
      extension: "",
      accept: "image/*, .pdf",
      filename: "",
      required: true,
      tab: 0,
    },
  
    {
      display: "Comprobante de domicilio",
      docBase64: "",
      documentoTipo: "address",
      extension: "",
      accept: "image/*, .pdf",
      filename: "",
      required: true,
      tab: 0,
    },
    {
      display: "Estado de cuenta",
      docBase64: "",
      documentoTipo: "estadoDeCuenta",
      extension: "",
      accept: "image/*, .pdf",
      filename: "",
      required: false,
      tab: 0,
    },
    {
      display: "Poder notariado del representante Legal",
      docBase64: "",
      documentoTipo: "representante1Poder",
      extension: "",
      accept: "image/*, .pdf",
      filename: "",
      required: false,
      tab: 0,
    },
    {
      display: "Poder notariado del representante Legal",
      docBase64: "",
      documentoTipo: "representante2Poder",
      extension: "",
      accept: "image/*, .pdf",
      filename: "",
      required: false,
      tab: 0,
    },
    {
      display: "Poder notariado del representante Legal",
      docBase64: "",
      documentoTipo: "representante3Poder",
      extension: "",
      accept: "image/*, .pdf",
      filename: "",
      required: false,
      tab: 0,
    },
    {
      display: "Poder notariado del representante Legal",
      docBase64: "",
      documentoTipo: "representante4Poder",
      extension: "",
      accept: "image/*, .pdf",
      filename: "",
      required: false,
      tab: 0,
    },
    {
      display: "Poder legal",
      docBase64: "",
      documentoTipo: "representante5Poder",
      extension: "",
      accept: "image/*, .pdf",
      filename: "",
      required: false,
      tab: 0,
    },
    {
      display: "Identificación oficial",
      docBase64: "",
      documentoTipo: "representante1INE",
      extension: "",
      accept: "image/*, .pdf",
      filename: "",
      required: true,
      tab: 0,
    },
    {
      display: "Identificación oficial",
      docBase64: "",
      documentoTipo: "representante2INE",
      extension: "",
      accept: "image/*, .pdf",
      filename: "",
      required: false,
      tab: 0,
    },
    {
      display: "Identificación oficial",
      docBase64: "",
      documentoTipo: "representante3INE",
      extension: "",
      accept: "image/*, .pdf",
      filename: "",
      required: false,
      tab: 0,
    },
    {
      display: "Identificación oficial",
      docBase64: "",
      documentoTipo: "representante4INE",
      extension: "",
      accept: "image/*, .pdf",
      filename: "",
      required: false,
      tab: 0,
    },
    {
      display: "Identificación oficial",
      docBase64: "",
      documentoTipo: "representante5INE",
      extension: "",
      accept: "image/*, .pdf",
      filename: "",
      required: false,
      tab: 0,
    },
  ];