import { useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import styles from "@app/styles/Home.module.css";
import LoginLayout from "@app/layout/login";
import { ButtonLoader } from "@app/components/Buttons";

import "primereact/resources/themes/lara-light-indigo/theme.css"; //theme
import "primereact/resources/primereact.min.css"; //core css
import "primeicons/primeicons.css"; //icons
import Link from "next/link";
import { FormItem } from "@app/components/FormManager/FormItem";
import { InputText } from "primereact/inputtext";
import { LoginControllers } from "@app/logic/backend/login";
import { toast } from "react-toastify";

export default function ForgotPassword() {
  const [email, setEmail] = useState("");
  const router = useRouter();
  const handleClick = async () => {
    const res = await LoginControllers.ForgotPassword(email);
    if (res.isSuccess && res.response.code === "200") {
      toast.success(res.response?.msg);
      router.back();
    } else {
      toast.error(res.response?.msg ?? "");
    }
  };

  return (
    <>
      <Head>
        <title>Iniciar Sesion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <LoginLayout>
          <h3
            style={{
              fontFamily: "urbanist_bold",
              fontSize: 20,
              marginBottom: -4,
              color: '#FFF'
            }}
          >
            Olvidé mi contraseña
          </h3>
          <FormItem className="my-5" label="Correo electrónico" labelClassName="text-[#FFF]">
            <InputText
              value={email}
              className="login-inputs"
              onChange={(e) => setEmail(e.target.value)}
              placeholder="Ingresa tu correo electrónico"
              style={{
                fontFamily: "urbanist_bold",
                paddingLeft: 21,
              }}
            />
          </FormItem>
        <div className="flex items-center justify-between mt-[-18px] mb-5">
          <ButtonLoader
            style={{
              paddingLeft: 46,
              paddingRight: 46,
              paddingTop: 13,
              paddingBottom: 13,
              textAlign: "center",
              justifyContent: "center",
              backgroundColor: "var(--primary-color)",
              color: '#FFF',
              borderRadius: 25,
              width: 188.5,
              fontFamily: "urbanist_bold",
            }}
            onClick={handleClick}
            disabled={!email}
          >
            Enviar
          </ButtonLoader>
          </div>
          <div className="flex items-center">
            <div className="flex justify-center text-[#FFF]">¿Ya tienes cuenta?</div>
            <Link
              href="/"
              className="font-medium no-underline ml-2 text-sm text-right cursor-pointer"
              style={{ color: "#FFF" }}
              >
                Inicia sesión
            </Link>
          </div>
        </LoginLayout>
      </main>
    </>
  );
}
