#  This is a basic workflow to help you get started with Actions
name: CentralAdmin
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_webapi:
    name: Build WebApp1
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Create a file
      run: echo "hello world" > my-file.txt
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact # NOTE: same artifact name
        path: my-file.txt

    - name: Downlod Artifacts 
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
        path: my-artifact
    - run: ls -R my-artifact
    
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.12.0
      with:
        target: 'https://centumpaycentraladmin.centum.mx/'
